local M = {}
local empty_buffers = require("config.empty_buffers")

local function back_to_dashboard()
    pcall(vim.cmd, "DashboardHome")
    empty_buffers.cleanup({
        keep = { vim.api.nvim_get_current_buf() },
    })
end

function M.open()
    vim.cmd("enew")
    vim.bo.buftype = "nofile"
    vim.bo.bufhidden = "wipe"
    vim.bo.swapfile = false
    vim.bo.modifiable = true
    vim.b.config_about_neovim = true
    vim.wo.cursorline = true
    empty_buffers.cleanup({
        keep = { vim.api.nvim_get_current_buf() },
    })

    local version = vim.version()
    local version_text = string.format(
        "ver. %d.%d.%d",
        version.major,
        version.minor,
        version.patch
    )

    local lines = {
        "",
        "  NVIM  " .. version_text,
        "  ─────────────────────────────────────",
        "",
        "  < Back",
        "",
        "  빠른 시작",
        "",
        "    Ctrl-s             일반 파일 저장",
        "    Space h            대시보드로 돌아가기",
        "    Space Ctrl-s       설정 메뉴 열기",
        "    Space e            파일 트리 열기/닫기",
        "    Space ff           파일명 검색",
        "    Space fg           프로젝트 전체 문자열 검색",
        "    Space bb           버퍼 선택",
        "    Space q / Q        현재 버퍼 닫기/강제 닫기",
        "    Space Ctrl-q       현재 창 닫기",
        "",
        "  LSP / 진단",
        "",
        "    gd                 정의로 이동",
        "    K                  hover 문서 보기",
        "    Space rn           심볼 이름 변경",
        "    Space ca           code action",
        "    Space dl           현재 줄 진단 보기",
        "    [d / ]d            이전/다음 진단으로 이동",
        "    :LSPSettings       LSP 설정 메뉴",
        "    :LSPMyList         LSP 서버 목록",
        "    :LSPMyInstall      LSP 서버 설치",
        "    :LSPMyUninstall    LSP 서버 제거",
        "    :Mason             Mason 관리 화면",
        "",
        "  디버깅 / DAP",
        "",
        "    F5                 디버깅 시작/계속 실행",
        "    F6                 step over",
        "    F7                 step into",
        "    F8                 step out",
        "    F9                 현재 줄 breakpoint 켜기/끄기",
        "    Space db           현재 줄 breakpoint 켜기/끄기",
        "    Space do           step over",
        "    Space di           step into",
        "    Space dO           step out",
        "    Space dB           조건부 breakpoint 추가",
        "    Space dL           logpoint 추가",
        "    Space du           디버깅 UI 열기/닫기",
        "    Space dr           디버깅 REPL 열기",
        "    Space dK           커서 위치/선택 영역 값 평가",
        "    Space dq           디버깅 세션 종료",
        "    :DapContinue       디버깅 시작/계속 실행",
        "    :DapToggleBreakpoint",
        "                       현재 줄 breakpoint 켜기/끄기",
        "    :DAPSettings       Debugger 설정 메뉴",
        "    :DAPMyList         DAP adapter 목록",
        "    :DAPMyInstall      DAP adapter 설치",
        "    :DAPMyUninstall    DAP adapter 제거",
        "    :Mason             debug adapter 설치 화면",
        "    Args prompt        Settings > Debugger 에서 켜기/끄기",
        "    Python args        F5 후 Args 입력창에 실행 인자 입력",
        "    C/C++/Rust args    F5 후 Executable, Args 입력창에 입력",
        "    Adapter 예시       codelldb(C/C++/Rust), debugpy(Python), delve(Go)",
        "    동작 조건          언어별 debug adapter 설치 및 프로젝트 실행 설정 필요",
        "",
        "  자동완성 / 스니펫",
        "",
        "    Ctrl-Space         자동완성 후보 열기",
        "    Ctrl-n / Ctrl-p    자동완성 후보 이동",
        "    Enter              선택한 자동완성 후보 확정",
        "    Ctrl-e             자동완성 후보 닫기",
        "    Tab / Shift-Tab    스니펫 위치 이동",
        "    Space ct           자동완성 켜기/끄기",
        "    Space st           스니펫 자동완성 후보 켜기/끄기",
        "    Space sr           custom snippets까지 다시 불러오기",
        "    :SnippetSettings   스니펫 설정 메뉴",
        "    Custom snippets    stdpath(config)/snippets 에 작성",
        "    Snippet format     VSCode JSON snippets 형식",
        "",
        "  검색 / 탐색",
        "",
        "    Space ff           파일명 검색",
        "    Space fg           프로젝트 전체 문자열 검색",
        "    Space fb           열린 버퍼 검색",
        "    Space fh           도움말 검색",
        "    Space sw           커서 위치 단어로 문자열 검색",
        "    Space ss           선택한 문자열로 검색",
        "",
        "  Git",
        "",
        "    Space gg           LazyGit 열기",
        "    Space gG           현재 파일 기준 LazyGit 열기",
        "    Space gf           현재 파일 git history 열기",
        "    Space gc           LazyGit config 열기",
        "    Space gp           현재 hunk 미리보기",
        "    Space gb           현재 줄 blame",
        "    Space gr           현재 hunk 되돌리기",
        "    ]c / [c            다음/이전 git hunk",
        "    LazyGit q          종료",
        "    LazyGit Esc        내부 취소/뒤로가기",
        "",
        "  파일 트리",
        "",
        "    Space e            파일 트리 열기/닫기",
        "    Enter / o          파일은 A 윈도우에 열기, 폴더는 열기/닫기",
        "    Double click       파일은 A 윈도우에 열기",
        "    w                  윈도우 피커로 파일 열기",
        "    O                  윈도우 피커 없이 파일 열기",
        "    s / v              선택 윈도우에 가로/세로 분할 후 파일 열기",
        "    Tab                파일 미리보기 열기/닫기",
        "    Esc                미리보기 닫기, 없으면 workspace root로 복귀",
        "    Ctrl-l / Right     미리보기 창으로 이동",
        "    Ctrl-h / Left      미리보기에서 파일 트리로 이동",
        "    a / r              파일 생성/이름 변경",
        "    d / D              휴지통으로 이동/영구 삭제",
        "    x / c / p          잘라내기/복사/붙여넣기",
        "    y / Y / gy         파일명/상대 경로/절대 경로 복사",
        "    m / bt / bd        북마크 토글/북마크를 휴지통으로/영구 삭제",
        "    - / P              트리 root를 부모로/커서를 부모 폴더로 이동",
        "    K / J              현재 폴더의 첫/마지막 항목으로 이동",
        "    < / >              이전/다음 형제 항목으로 이동",
        "    E / W              전체 폴더 펼치기/접기",
        "    L                  빈 폴더 그룹 표시 토글",
        "    R                  새로고침",
        "    H / I              숨김 파일/gitignore 파일 표시 토글",
        "    B / C              열린 버퍼 없음/git 변경 없음 필터 토글",
        "    M / U              북마크 없음/사용자 정의 필터 토글",
        "    f / F              필터 검색 시작/해제",
        "    [c / ]c            이전/다음 git 변경 항목",
        "    [e / ]e            이전/다음 진단 항목",
        "    S                  파일 검색 후 트리에서 이동",
        "    g?                 전체 파일 트리 단축키 도움말",
        "",
        "  버퍼",
        "",
        "    Space bb           버퍼 선택",
        "    Enter              버퍼 열기/포커스",
        "    w                  선택 윈도우에 버퍼 표시",
        "    m                  선택 윈도우로 버퍼 이동/교체",
        "    s / v              가로/세로 분할에 버퍼 열기",
        "    d / D              버퍼 삭제/강제 삭제",
        "    o / O              선택 항목만 남기기/강제 적용",
        "    Space bn / bp      다음/이전 버퍼",
        "    Space bm           현재 버퍼를 선택 윈도우로 이동/교체",
        "    Space bw           현재 버퍼를 선택 윈도우에 표시",
        "    Space bd / bD      현재 버퍼 닫기/강제 닫기",
        "    Space bo / bO      다른 버퍼 닫기/강제 닫기",
        "    실패 시            목록을 유지하고 오류 메시지 표시",
        "",
        "  창",
        "",
        "    Space ww           창 선택",
        "    Space wr           현재 창 라벨을 선택 창과 교환",
        "    Space wv           세로 분할",
        "    Space ws           가로 분할",
        "    Space wo           현재 창만 남기기",
        "    Space wq           현재 창 닫기",
        "    Ctrl-h/j/k/l       왼쪽/아래/위/오른쪽 창 이동",
        "    Ctrl-Arrow         방향키로 창 이동",
        "    Alt-h/l            창 너비 1칸 줄이기/늘리기",
        "    Alt-k/j            창 높이 1칸 늘리기/줄이기",
        "    Alt-Arrow          방향키로 창 크기 1칸 조절",
        "    창 라벨            파일 트리 제외, 생성 순서대로 A/B/C",
        "",
        "  탭",
        "",
        "    Space Tab Tab      탭 목록 플로팅창 열기",
        "    Space Tab n        새 탭",
        "    Space Tab q        현재 탭 닫기",
        "    Space Tab h/l      이전/다음 탭",
        "    Space Tab ←/→      이전/다음 탭",
        "    탭 목록            현재 탭 위치에 커서, Enter 이동, Esc 닫기",
        "    상단 탭 표시       탭이 2개 이상일 때 󰓩 00 버퍼명 형식으로 표시",
        "    탭 색상            현재 컬러스키마 highlight 기준으로 자동 적용",
        "",
        "  터미널 / 플로팅",
        "",
        "    Space tt           현재 창에 버퍼 터미널 생성",
        "    Space ts           현재 창에서 가로 분할 후 버퍼 터미널 생성",
        "    Space tv           현재 창에서 세로 분할 후 버퍼 터미널 생성",
        "    Space tc           현재 터미널을 새 버퍼로 초기화",
        "    Space 0~9          번호 플로팅 파일 슬롯 열기/숨기기",
        "    Space q / Q        플로팅 슬롯 버퍼 닫기/강제 닫기",
        "    Esc                터미널 모드에서 노멀 모드로 전환",
        "    Space bb           터미널 버퍼 선택/이동/삭제",
        "    :TKill             현재 터미널 종료",
        "    플로팅 슬롯        [F1] 형식, 검색/grep 결과를 해당 슬롯에 열기",
        "    Space 백틱 / ~     백틱 플로팅 파일 슬롯 열기/숨기기",
        "    전환 규칙          플로팅 슬롯은 하나만 표시, 새 슬롯을 열면 기존 슬롯 숨김",
        "    슬롯 터미널        슬롯에서 Space tt로 생성, Space bb로 선택/이동/삭제",
        "",
        "  세션",
        "",
        "    Space pp           세션 목록 열기",
        "    Space p0~p9        0~9번 세션 불러오기",
        "    Space P0~P9        현재 세션을 0~9번에 저장",
        "    Enter              세션 목록에서 선택 세션 불러오기",
        "    w                  현재 세션을 선택 슬롯에 저장",
        "    m                  이동 대상 선택 시작, Enter/m/번호로 확정, 대상이 있으면 서로 교체",
        "    n                  선택 세션 이름 지정/수정, 변경 시 Enter/y 확인",
        "    e                  선택 세션 노트 편집기 열기",
        "    d                  선택 세션 삭제, Enter/y 확인 필요",
        "    Tab                자동 미리보기가 없을 때 임시 미리보기 열기/닫기",
        "    Ctrl-u/d           normal mode에서 세션 미리보기 위/아래 스크롤",
        "    PageUp/PageDown    normal mode에서 세션 미리보기 위/아래 크게 스크롤",
        "    Esc                임시 미리보기가 열려 있으면 닫기, 아니면 세션 목록 닫기",
        "    insert Esc         세션/Telescope 목록에서 normal mode로 전환",
        "    :SessionSave 3     현재 세션을 3번 슬롯에 저장",
        "    :SessionLoad 3     3번 세션 불러오기",
        "    :SessionMove 1 4   1번을 4번으로 이동, 4번이 있으면 서로 교체",
        "    :SessionName 3     3번 세션 이름 지정/수정",
        "    :SessionNote 3     3번 세션 메모 작성/수정",
        "    :SessionDelete 3   3번 세션 삭제, Enter/y 확인 필요",
        "    슬롯 설정          lua/config/sessions.lua 상단 session_slot_ids 수정",
        "    ! 표시             현재 키맵에는 없지만 저장 파일이 남아 있는 세션",
        "    저장 확인          빈 슬롯은 바로 저장, 기존 슬롯은 Enter/y 확인 후 덮어쓰기",
        "    노트 편집          줄바꿈/탭 입력 가능, Ctrl-s 또는 normal Enter로 저장 확인",
        "    노트 Esc           변경 없음은 바로 닫기, 변경 있음은 폐기 y 확인",
        "    이름 입력          값이 같으면 종료, 변경 시 y 확인, Esc로 취소",
        "    저장 위치          stdpath(state)/sessions/slot-N.json",
        "    복원 범위          tab, split, buffer, cursor, terminal, tree, dashboard, breakpoint, 빈 창, floating slot",
        "    터미널 한계        실행 중이던 프로세스는 복구하지 않고 새 shell을 다시 생성",
        "",
        "  대시보드 / About",
        "",
        "    Dashboard e        새 파일",
        "    Dashboard f        파일명 검색",
        "    Dashboard g        프로젝트 전체 문자열 검색",
        "    Dashboard w        작업 폴더 변경",
        "    Dashboard t        파일 트리 열기/닫기",
        "    Dashboard s        설정 메뉴 열기",
        "    Dashboard a        About Neovim 열기",
        "    Dashboard q        안전 종료 확인",
        "    Dashboard Q        blocker가 있을 때 강제 종료 확인",
        "    Dashboard Enter    blocker가 없을 때 Neovim 종료",
        "    Dashboard Esc      종료 확인 취소",
        "    Space q            직전 버퍼/터미널 복귀, 없으면 창 닫기 또는 종료",
        "    About h / b / Esc  대시보드로 돌아가기",
        "    About q / Q        About 닫기/강제 닫기",
        "    Space+버튼 키      전역 단축키가 없으면 대시보드 버튼 실행 방지",
        "",
        "  Tree-sitter",
        "",
        "    za                 현재 위치 접기 열기/닫기",
        "    zc / zo            현재 위치 접기 닫기/열기",
        "    zM / zR            전체 접기 닫기/열기",
        "    zm / zr            접기 레벨 줄이기/늘리기",
        "    :TSSettings        Tree-sitter 설정 메뉴",
        "    :TSMyList          설치된 parser 목록",
        "    :TSMyInstall rust  rust parser 설치 예시",
        "    :TSMyUninstall rust",
        "    :TSMyUpdate",
        "    기본 상태          파일을 열 때 자동으로 접지 않고 펼친 상태 유지",
        "    동작 조건          해당 언어 Tree-sitter parser 설치 필요",
        "",
        "  설정 / 관리",
        "",
        "    :help              Neovim 도움말 열기",
        "    :Tutor             Vim 기본 튜토리얼",
        "    :checkhealth       현재 환경 상태 검사",
        "    :version           Neovim 버전 정보",
        "    :messages          최근 메시지 확인",
        "    :Lazy              플러그인 관리 화면",
        "    :Lazy install      새 플러그인 설치",
        "    :Lazy sync         플러그인 설치/업데이트",
        "    :ThemePick         테마 선택 메뉴",
        "    줄번호 설정 위치   lua/config/options.lua",
        "    일반 줄번호        vim.opt.number = true",
        "    상대 줄번호        vim.opt.relativenumber = true 로 변경",
        "    표시 방식          현재 줄은 실제 번호, 위/아래 줄은 현재 줄과의 거리",
        "",
        "  테마",
        "",
        "    기본 내장 테마     Neovim 내장 colorscheme 전체",
        "    고정 설치 테마     + vscode, + onedark, + tokyonight",
        "    테마 추가 위치     lua/plugins/themes.lua",
        "    추가 방법          플러그인 spec 추가 후 colorschemes 에 테마명 등록",
        "    예시               { \"catppuccin/nvim\", colorschemes = { \"catppuccin\" } }",
        "",
        "  주석 및 42header",
        "",
        "    gcc                현재 줄 주석 토글",
        "    gc                 visual 선택 영역 줄 주석 토글",
        "    gc{motion}         motion 범위 줄 주석 토글, 예: gcip",
        "    gbc                현재 줄 블록 주석 토글",
        "    gb                 visual 선택 영역 블록 주석 토글",
        "    gb{motion}         motion 범위 블록 주석 토글",
        "    gco / gcO          아래/위 줄에 주석 추가 후 입력 모드",
        "    gcA                현재 줄 끝에 주석 추가 후 입력 모드",
        "    Insert Ctrl-l      다음 괄호/따옴표 밖으로 이동",
        "    :Stdheader         현재 파일에 42 헤더 추가/갱신",
        "    Insert F1          42 헤더 추가/갱신",
        "",
        "  42 Header 설정",
        "",
        "    NAME               42 intra id 환경변수",
        "    MAIL               42 email 환경변수",
        "    ~/.zshrc           아래 두 줄 추가",
        "    export NAME=\"your_intra_id\"",
        "    export MAIL=\"your_email@student.42seoul.kr\"",
        "    적용               source ~/.zshrc 후 Neovim 재시작",
        "",
        "  종료",
        "",
        "    Space wq           현재 창 닫기",
        "    Space Ctrl-q       현재 창 닫기",
        "    Space q / Q        현재 버퍼 닫기/강제 닫기, hidden 버퍼 우선 복귀",
        "    Dashboard q        안전 종료, blocker가 있으면 Q로 강제 종료",
        "    :q                 현재 창 닫기",
        "    :qa                Neovim 종료",
        "    :qa!               강제 종료",
        "",
    }

    vim.api.nvim_buf_set_lines(0, 0, -1, false, lines)
    vim.bo.modifiable = false
    vim.bo.filetype = "help"

    vim.api.nvim_win_set_cursor(0, { 5, 2 })

    vim.keymap.set("n", "<CR>", function()
        if vim.api.nvim_win_get_cursor(0)[1] == 5 then
            back_to_dashboard()
        end
    end, {
        buffer = true,
        silent = true,
        desc = "Back to dashboard",
    })

    vim.keymap.set("n", "h", back_to_dashboard, {
        buffer = true,
        silent = true,
        desc = "Back to dashboard",
    })

    vim.keymap.set("n", "b", back_to_dashboard, {
        buffer = true,
        silent = true,
        desc = "Back to dashboard",
    })

    vim.keymap.set("n", "<Esc>", back_to_dashboard, {
        buffer = true,
        silent = true,
        desc = "Back to dashboard",
    })

    vim.keymap.set("n", "<leader>h", back_to_dashboard, {
        buffer = true,
        silent = true,
        desc = "Back to dashboard",
    })

    vim.keymap.set("n", "q", ":bd<CR>", {
        buffer = true,
        silent = true,
        desc = "Close About Neovim",
    })

    vim.keymap.set("n", "Q", ":bd!<CR>", {
        buffer = true,
        silent = true,
        desc = "Force close About Neovim",
    })
end

return M
